version: 2.1
orbs:
  node: circleci/node@2.0.2
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
          steps:
            - run: npm install
            - run: npm run test && make test-coverage
            - coveralls/upload
workflows:
    matrix-tests:
      jobs:
        - node/test:
            version: 13.11.0
        - node/test:
            version: 12.16.0
        - node/test:
            version: 10.19.0
    build-and-test:
      jobs:
        - build-and-test
