DROP TABLE IF EXISTS company CASCADE;
DROP TABLE IF EXISTS admin_info CASCADE;
DROP TABLE IF EXISTS user_info CASCADE;
DROP TABLE IF EXISTS facility CASCADE;
DROP TABLE IF EXISTS device CASCADE;
DROP TABLE IF EXISTS tank CASCADE;
DROP TABLE IF EXISTS activity_logs CASCADE;
DROP TABLE IF EXISTS device CASCADE;
DROP TABLE IF EXISTS tanker_data CASCADE;
DROP TABLE IF EXISTS contact_us;
DROP TYPE tank_structure_type;
DROP TYPE company_subscription_type;
DROP TYPE company_subscription_status;
DROP TYPE facility_facility_type;
DROP TYPE user_user_type;
